"""add listing indexes

Revision ID: 365209926f3a
Revises: 767e57088548
Create Date: 2026-05-24 17:08:13.317687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365209926f3a'
down_revision: Union[str, Sequence[str], None] = '767e57088548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_listings_is_active', 'listings', ['is_active'], unique=False)
    op.create_index('ix_listings_listed_at', 'listings', ['listed_at'], unique=False)
    op.create_index('ix_listings_make_model_year', 'listings', ['make', 'model', 'year'], unique=False)
    op.create_index('ix_listings_price', 'listings', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_listings_price', table_name='listings')
    op.drop_index('ix_listings_make_model_year', table_name='listings')
    op.drop_index('ix_listings_listed_at', table_name='listings')
    op.drop_index('ix_listings_is_active', table_name='listings')
    # ### end Alembic commands ###
